# -*- coding: utf-8 -*-
"""Multi Linear Regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18bpl2sYxB0HYPVmyYHeN9nTrATTfUSMT
"""

from sklearn.datasets import fetch_california_housing

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

california = fetch_california_housing()

print(df)

california.keys()

print(california.DESCR)

print(california.data)

print(california.feature_names)

print(california.target)

column = california.feature_names
data = california.data

df = pd.DataFrame(california.data, columns = california.feature_names)

df['target'] = california.target

df.head()

df.info()

df.isnull().sum()

df.describe()

x = df.drop('target', axis = 1)
y = df['target']

print(x)

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.33,random_state=10)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train,y_train)
print(lr.coef_,lr.intercept_)

y_pred = lr.predict(x_test)

print(y_pred)

from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error
from sklearn.metrics import r2_score

mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = root_mean_squared_error(y_test, y_pred)
score = r2_score(y_test, y_pred)

print("Mean Absolute Error : ", mae)
print("Mean Squared Error : ", mse)
print("Root Mean Squared Error : ", rmse)
print("R2 score : ", score)

adjusted_r_squared = 1-(1-score)*(len(y_test) - 1)/(len(y_test) - x_test.shape[1] - 1)
print("Adjusted R2 score : ", adjusted_r_squared)

